<?php
/**
 * Created by PhpStorm.
 * User: xiongxin
 * Date: 2016/4/11
 * Time: 14:19
 */

class ArticleController extends Core\Wechat  {
    function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->raw_data = json_to_array(file_get_contents('php://input'));
    }

    function addAction() {
        $article_id = $this->raw_data['body']['id'];

        $item = M('t_document(a)')->get(
            [
                '[>]t_document_article(b)'=>['a.id'=>'id'],
            ],
            [
                'a.title',
                'a.cover_id',
                'b.content',
                'a.description',
            ],
            [
                'AND'=>[
                    'a.id' => $article_id
                ]
            ]);
        $item['cover_id'] = get_qiniu_file_durl($item['cover_id']);
        $filename = '/tmp/' . uniqid() . '.png';
        $fc = file_get_contents($item['cover_id']); //读取七牛图片内容
        file_put_contents($filename, $fc); //写入到临时图片文件
        $result = $this->wechat->uploadForeverMedia(['media'=>new CURLFile($filename)], 'image');//将封面上传至维信服务器
        if(is_array($result) && isset($result['media_id'])){
            $data = [
                'title'=> $item['title'],
                'thumb_media_id' => $result['media_id'],
                'digest' => $item['description'],
                'show_cover_pic' => 1,
                'content' => $item['content']
            ];
            //上传文章
            $result = $this->wechat->uploadForeverArticles(['articles'=>[$data]]);
            if (is_array($result) && isset($result['media_id'])) {
                return M('t_document_article')->update(['media_id'=>$result['media_id']],
                    ['id'=>$article_id]); //更新数据库
            }
        }
        die();
    }

    function editAction() {
        $article_id = $this->raw_data['body']['id'];
        $item = M('t_document(a)')->get(
            [
                '[>]t_document_article(b)'=>['a.id'=>'id'],
            ],
            [
                'a.title',
                'a.cover_id',
                'b.content',
                'a.description',
                'b.media_id'
            ],
            [
                'AND'=>[
                    'a.id' => $article_id
                ]
            ]);

        if ( stripos($item['cover_id'],"http://") !==FALSE ) {
            $item['cover_id'] = get_qiniu_file_durl($item['cover_id']);
            $filename = '/tmp/' . uniqid() . '.png';
            $fc = file_get_contents($item['cover_id']); //读取七牛图片内容
            file_put_contents($filename, $fc); //写入到临时图片文件
            $result = $this->wechat->uploadForeverMedia(['media'=>new CURLFile($filename)], 'image');//将封面上传至维信服务器
            if(is_array($result) && isset($result['media_id'])){
                $data = [
                    'title'=> $item['title'],
                    'thumb_media_id' => $result['media_id'],
                    'digest' => $item['description'],
                    'show_cover_pic' => 1,
                    'content' => $item['content'],
                ];
                return $this->wechat->updateForeverArticles($item['media_id'], ['articles'=>$data]);
            }
        } else {
            $data = [
                'title'=> $item['title'],
                'digest' => $item['description'],
                'show_cover_pic' => 1,
                'content' => $item['content'],
            ];

            return $this->wechat->updateForeverArticles($item['media_id'], ['articles'=>$data]);
        }

        die();
    }

    function deleteAction() {
        $article_id = $this->raw_data['body']['id'];
        if (empty($article_id)) $this->error('没有添加到微信素材中!');
        $article = M('t_document_article(a)')->get(['a.media_id'], ['a.id'=>$article_id]);
        if ( $this->wechat->delForeverMedia($article['media_id'])) {
            M('t_document_article')->update(['media_id'=>''],
                ['id'=>$article_id]); //更新数据库
        }

        die();
    }
}